apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin-credentials
  namespace: ecommerce-namespace
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
